export const ERROR_SUFFIX = '_ERROR';

export const GET_PROJECTS = 'GET_PROJECTS';
export const CREATE_PROJECT = 'CREATE_PROJECT';
export const UPDATE_PROJECT = 'UPDATE_PROJECT';
export const DELETE_PROJECT = 'DELETE_PROJECT';
export const SET_PROJECT_CLOAKED = 'SET_PROJECT_CLOAKED';
export const GET_INVOICING = 'GET_INVOICING';
export const GET_BILLABLE_PROJECTS = 'GET_INVOICING_PROJECTS';
export const LOGIN = 'LOGIN';
export const LOGOUT = 'LOGOUT';
export const OPEN_MESSAGE = 'OPEN_MESSAGE';
export const CLOSE_MESSAGE = 'CLOSE_MESSAGE';
export const SET_SELECTED_PROJECT = 'SET_SELECTED_PROJECT';
export const GET_WORK = 'GET_WORK';
