export const GET_PROJECTS = 'GET_PROJECTS';
export const CREATE_PROJECT = 'CREATE_PROJECT';
export const UPDATE_PROJECT = 'UPDATE_PROJECT';
export const SET_PROJECT_CLOAKED = 'SET_PROJECT_CLOAKED';
export const GET_INVOICING = 'GET_INVOICING';
export const GET_INVOICING_PROJECTS = 'GET_INVOICING_PROJECTS';
export const LOGIN = 'LOGIN';
export const LOGOUT = 'LOGOUT';
